{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.networkService.port -}}
{{- $svcName := "" -}}
{{- if eq .Values.topology.mode "standalone" -}}
{{- $svcName = include "nemo-retriever.fullname" . -}}
{{- else -}}
{{- $svcName = include "nemo-retriever.role.fullname" (dict "context" $ "role" "gateway") -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nemo-retriever.fullname" . }}
  labels:
    {{- include "nemo-retriever.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
