{{- if and (and (.Capabilities.APIVersions.Has "apps.nvidia.com/v1alpha1") .Values.nims.enabled) (eq .Values.nimOperator.rerankqa.enabled true) -}}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: llama-nemotron-rerank-vl-1b-v2
  {{- include "nemo-retriever.nimcache.keepPolicy" . | nindent 2 }}
spec:
  source:
    ngc:
      modelPuller: "{{ .Values.nimOperator.rerankqa.image.repository }}:{{ .Values.nimOperator.rerankqa.image.tag }}"
      pullSecret: "{{ index .Values.nimOperator.rerankqa.image.pullSecrets 0 }}"
      authSecret: {{ .Values.nimOperator.rerankqa.authSecret }}
      {{- include "nemo-retriever.nimcache.modelBlock" (dict "context" $ "key" "rerankqa") | nindent 6 }}
  storage:
    pvc:
      create: {{ .Values.nimOperator.rerankqa.storage.pvc.create }}
      storageClass: {{ .Values.nimOperator.rerankqa.storage.pvc.storageClass | quote }}
      size: {{ .Values.nimOperator.rerankqa.storage.pvc.size }}
      volumeAccessMode: {{ .Values.nimOperator.rerankqa.storage.pvc.volumeAccessMode }}
  nodeSelector:
{{ toYaml .Values.nimOperator.rerankqa.nodeSelector | indent 4 }}
  tolerations:
{{ toYaml .Values.nimOperator.rerankqa.tolerations | indent 4 }}
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: llama-nemotron-rerank-vl-1b-v2
spec:
  image:
    repository: {{ .Values.nimOperator.rerankqa.image.repository }}
    tag: {{ .Values.nimOperator.rerankqa.image.tag }}
    pullPolicy: {{ .Values.nimOperator.rerankqa.image.pullPolicy }}
    pullSecrets:
{{ toYaml .Values.nimOperator.rerankqa.image.pullSecrets | indent 6 }}
  authSecret: {{ .Values.nimOperator.rerankqa.authSecret }}
  storage:
    nimCache:
      name: llama-nemotron-rerank-vl-1b-v2
  replicas: {{ .Values.nimOperator.rerankqa.replicas }}
  nodeSelector:
{{ toYaml .Values.nimOperator.rerankqa.nodeSelector | indent 4 }}
  {{- include "nemo-retriever.nimServiceResources" (dict "context" $ "resources" .Values.nimOperator.rerankqa.resources) | nindent 2 }}
  tolerations:
{{ toYaml .Values.nimOperator.rerankqa.tolerations | indent 4 }}
  expose:
{{ toYaml .Values.nimOperator.rerankqa.expose | indent 4 }}
  env:
{{ include "nemo-retriever.nimServiceOtelEnv" (dict "context" $ "key" "rerankqa" "name" "llama-nemotron-rerank-vl-1b-v2") | nindent 4 }}
{{ toYaml .Values.nimOperator.rerankqa.env | indent 4 }}
{{- end }}
